books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    # Books CRUD
    path('', views.BookListView.as_view(), name='index'),
    path('<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('create/', views.BookCreateView.as_view(), name='book_create'),
    path('<int:pk>/update/', views.BookUpdateView.as_view(), name='book_update'),
    path('<int:pk>/delete/', views.BookDeleteView.as_view(), name='book_delete'),
]

# Categories CRUD
urlpatterns += [
    path('categories/', views.CategoryListView.as_view(), name='category_list'),
    path(
        'categories/<int:pk>/',
        views.CategoryDetailView.as_view(),
        name='category_detail'
    ),
    path(
        'categories/create/',
        views.CategoryCreateView.as_view(),
        name='category_create'
    ),
    path(
        'categories/<int:pk>/update/',
        views.CategoryUpdateView.as_view(),
        name='category_update'
    ),
    path(
        'categories/<int:pk>/delete/',
        views.CategoryDeleteView.as_view(),
        name='category_delete'
    ),
]

# Report views
urlpatterns += [
    path('import-books', views.import_books, name='import_books'),
    path('expenses-dashboard', views.expenses_dashboard, name='expenses_dashboard'),
]

rumi_press/urls.py
from django_registration.backends.one_step.views import RegistrationView
from debug_toolbar.toolbar import debug_toolbar_urls
from books_auth.forms import RegistrationForm
from django.views.generic import TemplateView
from django.urls import path, include
from django.contrib import admin
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'accounts/register/',
        RegistrationView.as_view(form_class=RegistrationForm),
        name='django_registration_register'
    ),
    path(
        'accounts/profile/',
        TemplateView.as_view(template_name='registration/profile.html'),
        name='profile'
    ),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.home, name='home'),
    path('books/', include('books.urls')),
    path('api/v1/', include('books.api.urls')),
]


# Django debur toolbar urls
urlpatterns += debug_toolbar_urls()

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% block link_tags %}{% endblock link_tags %}

    <title>{% block title %}Rumi Press{% endblock title %}</title>
  </head>
  <body>
    <!-- Django Messages using Bootstrap Toasts -->
    {% if messages %}
      <div class="toast-container position-fixed bottom-0 end-0 p-3">
        {% for message in messages %}
          <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="true">
            <div class="toast-header">
              <strong class="me-auto">Notification</strong>
              <small class="text-muted">just now</small>
              <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body text-bg-{{ message.tags }}">
              {{ message }}
            </div>
          </div>
        {% endfor %}
      </div>
      <script>
        document.addEventListener('DOMContentLoaded', function () {
          var toastElList = [].slice.call(document.querySelectorAll('.toast'));
          toastElList.map(function (toastEl) {
            var toast = new bootstrap.Toast(toastEl);
            toast.show();
          });
        });
      </script>
    {% endif %}

    {% block content %}
    {% endblock content %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

templates/navbar.html
{% extends "base.html" %}
{% load cache %}

{% block content %}
<nav class="navbar navbar-dark bg-dark py-3 fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand fs-5" href="{% url 'books:index' %}">Rumi Press - Books Management</a>

        <div class="d-flex align-items-center">
            {% cache 600 authenticated_navbar request.user %}
            {% if user.is_authenticated and request.user.is_active %}
            <span class="navbar-text me-3 fs-6 text-light">Hello, {{ request.user.email }}</span>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn text-light fs-6">Logout</button>
            </form>
            {% else %}
            <a class="text-light fs-6" href="{% url 'login' %}">Login</a>
            {% endif %}
            {% endcache %}
        </div>
    </div>
</nav>
{% endblock content %}

templates/sidebar.html
{% extends "base.html" %}
{% load cache %}

{% block content %}
{% include "navbar.html" %}
<div class="d-flex">
    <!-- Sidebar -->
    <div class="d-flex flex-column flex-shrink-0 p-3 bg-dark text-white"
    style="width: 250px; height: 100vh; position: fixed; overflow-y: auto;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <span class="fs-4">Rumi Press</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column">
        <li class="nav-item">
            <a href="{% url 'books:index' %}" class="nav-link text-white">
                Books
            </a>
        </li>
        <li>
            <a href="{% url 'books:category_list' %}" class="nav-link text-white">
                Categories
            </a>
        </li>
        <li>
            <a href="{% url 'books:expenses_dashboard' %}" class="nav-link text-white">
                Expenses
            </a>
        </li>
    </ul>
    <hr>
    
    <!-- Show filters when appropiated -->
    {% block filter_form %}{% endblock filter_form %}
</div>

<!-- Main Content -->
<div class="flex-grow-1 p-4 mt-4" style="margin-left: 250px;">
    <!-- Add your main content here -->
    {% block sb_content %}{% endblock sb_content %}
</div>
</div>
{% endblock content %}