books/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('import-books', views.BulkBookCreateView.as_view(),
         name='api_import_books'),
    path(
        'create-category',
        views.CategoryCreateAPIView.as_view(),
        name='api_create_category'
    ),
]

books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    # Books CRUD
    path('', views.BookListView.as_view(), name='index'),
    path('<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('create/', views.BookCreateView.as_view(), name='book_create'),
    path('<int:pk>/update/', views.BookUpdateView.as_view(), name='book_update'),
    path('<int:pk>/delete/', views.BookDeleteView.as_view(), name='book_delete'),
]

# Categories CRUD
urlpatterns += [
    path('categories/', views.CategoryListView.as_view(), name='category_list'),
    path(
        'categories/<int:pk>/',
        views.CategoryDetailView.as_view(),
        name='category_detail'
    ),
    path(
        'categories/create/',
        views.CategoryCreateView.as_view(),
        name='category_create'
    ),
    path(
        'categories/<int:pk>/update/',
        views.CategoryUpdateView.as_view(),
        name='category_update'
    ),
    path(
        'categories/<int:pk>/delete/',
        views.CategoryDeleteView.as_view(),
        name='category_delete'
    ),
]

# Report views
urlpatterns += [
    path('import-books', views.import_books, name='import_books'),
    path('expenses-dashboard', views.expenses_dashboard, name='expenses_dashboard'),
]

rumi_press/urls.py
from django_registration.backends.one_step.views import RegistrationView
from debug_toolbar.toolbar import debug_toolbar_urls
from books_auth.forms import RegistrationForm
from django.views.generic import TemplateView
from django.urls import path, include
from django.contrib import admin
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'accounts/register/',
        RegistrationView.as_view(form_class=RegistrationForm),
        name='django_registration_register'
    ),
    path(
        'accounts/profile/',
        TemplateView.as_view(template_name='registration/profile.html'),
        name='profile'
    ),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.home, name='home'),
    path('books/', include('books.urls')),
    path('api/v1/', include('books.api.urls')),
]


# Django debur toolbar urls
urlpatterns += debug_toolbar_urls()

books/models.py
from django.db import models
from django.core.validators import MinLengthValidator

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Expense(models.Model):
    value = models.DecimalField(max_digits=7, decimal_places=2)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='expenses'
    )

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.value)


class Book(models.Model):
    title = models.CharField(
        max_length=400,
        validators=[MinLengthValidator(2)]
    )
    subtitle = models.CharField(max_length=500, blank=True, null=True)
    authors = models.CharField(
        max_length=500,
        validators=[MinLengthValidator(2)]
    )
    publisher = models.CharField(
        max_length=150,
        validators=[MinLengthValidator(3)]
    )
    published_date = models.DateField()
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE,
        related_name='books', null=True, blank=True
    )
    expense = models.DecimalField(
        max_digits=7, decimal_places=2, null=True, blank=True
    )

    def __str__(self):
        return self.title

books/forms.py
from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError
from .models import Category, Book, Expense
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from utils.pandas import validate_cols
from django import forms


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))


class BookForm(forms.ModelForm):
    authors = forms.CharField(
        label='Authors',
        max_length=255,
        widget=forms.TextInput(attrs={'placeholder': 'Author1, Author2'}),
    )

    class Meta:
        model = Book
        fields = ['title', 'subtitle', 'category', 'authors',
                  'publisher', 'published_date', 'expense']
        widgets = {
            'published_date': forms.DateInput(
                attrs={'type': 'date', 'class': 'form-control'}
            ),
            'expense': forms.NumberInput(attrs={'step': '0.01'}),
        }

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        # Adding crispy forms helper
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))


class ImportBooksForm(forms.Form):
    file = forms.FileField(
        label='Books Data',
        validators=[
            FileExtensionValidator(allowed_extensions=['csv'])],
        help_text='Upload a .xlsx file with the books data.',
        required=True,
        allow_empty_file=False,
        widget=forms.ClearableFileInput(
            attrs={'accept': '.csv', 'class': 'form-control'}),
    )

    def __init__(self, *args, **kwargs):
        super(ImportBooksForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

    def clean_file(self):
        # Check if the uploaded file is a valid spreadsheet

        COLS = [
            'title', 'subtitle', 'category', 'authors', 'publisher', 'published_date', 'distribution_expense'
        ]

        file = self.cleaned_data['file']
        try:
            import pandas as pd
            file = pd.read_csv(
                file,
                dtype=str,
                usecols=COLS,
                encoding='utf-8',
            )

            file.rename(
                columns={'distribution_expense': 'expense'}, inplace=True)
        except ValueError:
            raise ValidationError(f'Invalid file format or columns')

        return file

books/api/views.py
from rest_framework.authentication import TokenAuthentication, SessionAuthentication
from .serializers import BookBulkCreate, CategorySerializer
from rest_framework.permissions import IsAuthenticated
from rest_framework.generics import CreateAPIView
from rest_framework.response import Response
from django.shortcuts import redirect
from django.urls import reverse_lazy
from rest_framework import status


class BulkBookCreateView(CreateAPIView):
    """
    View to create multiple books at once.
    """
    serializer_class = BookBulkCreate
    permission_classes = [IsAuthenticated]

    # def create(self, request, *args, **kwargs):
    #     if isinstance(self.request.data, list):
    #         serializer = self.get_serializer(data=request.data, many=True)
    #         serializer.is_valid(raise_exception=True)
    #         serializer.save()
    #         return Response(serializer.data, status=status.HTTP_201_CREATED)
    #     else:
    #         serializer = self.get_serializer(data=request.data)
    #         serializer.is_valid(raise_exception=True)
    #         serializer.save()
    #         return Response(serializer.data, status=status.HTTP_201_CREATED)


class CategoryCreateAPIView(CreateAPIView):
    """
    View to create a category.
    """
    # permission_classes = [IsAuthenticated]
    # authentication_classes = [TokenAuthentication, SessionAuthentication]
    serializer_class = CategorySerializer

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()

        return redirect(reverse_lazy('books:book_create'))

books/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CategoryForm, BookForm, ImportBooksForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from rest_framework.authtoken.models import Token
from .filters import BookFilter, CategoriesFilter
from django.shortcuts import redirect, render
from django_filters.views import FilterView
from utils.pandas import format_dataframe
from utils.bokeh import generate_plot
from django.urls import reverse_lazy
from django.contrib import messages
from .models import Book, Category
from django.db.models import Sum
import logging

logger = logging.getLogger(__name__)

# Create your views here.

# Books CRUD


class BookListView(LoginRequiredMixin, FilterView, ListView):
    model = Book
    filterset_class = BookFilter
    paginate_by = 25
    context_object_name = 'books'
    template_name = 'books/book_list.html'

    def get_queryset(self):
        return Book.objects.prefetch_related('category').order_by('-id')


class BookDetailView(LoginRequiredMixin, DetailView):
    model = Book

    def get_queryset(self):
        return Book.objects.prefetch_related('category')


class BookCreateView(LoginRequiredMixin, CreateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('books:index')


class BookUpdateView(LoginRequiredMixin, UpdateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('books:index')


class BookDeleteView(LoginRequiredMixin, DeleteView):
    model = Book
    template_name = 'books/object_confirm_delete.html'
    success_url = reverse_lazy('books:index')


# categories CRUD


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category

    def get_queryset(self):
        return Category.objects.prefetch_related('books').annotate(
            total_expenses=Sum('books__expense')
        )


class CategoryDetailView(LoginRequiredMixin, DetailView):
    model = Category

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.prefetch_related('books').annotate(
            total_expenses=Sum('books__expense'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = Paginator(self.object.books.all(), 25)
        page = self.request.GET.get('page')

        try:
            paginated_books = paginator.page(page)
        except PageNotAnInteger:
            paginated_books = paginator.page(1)
        except EmptyPage:
            paginated_books = paginator.page(paginator.num_pages)

        # Add the paginated books to the context
        context['page_obj'] = paginated_books
        return context


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('books:category_list')


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('books:category_list')


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = Category
    template_name = 'books/object_confirm_delete.html'
    success_url = reverse_lazy('books:category_list')

# report views


@login_required
def report(request):
    pass


@login_required
def import_books(request):
    if request.method == 'POST':
        form = ImportBooksForm(request.POST, request.FILES)
        if form.is_valid():
            books = Book.objects.all()
            books = list(books.values_list('book_id', flat=True))

            # Process the uploaded file to make a Json
            import json
            file = form.cleaned_data['file']
            logger.debug(
                f'Duplicatd per title: {file.duplicated(subset=["title", "category"]).sum()}')
            # file = file.drop_duplicates(
            #     subset=['id'], keep='first')
            file = format_dataframe(file)
            json_data = json.loads(file.to_json(orient='records'))
            # Make a request to the api to create the books
            import requests
            token = Token.objects.get(user=request.user)
            response = requests.post(
                url='http://172.21.0.1:80/api/v1/import-books',
                json=json_data,
                headers={'Authorization': f'Token {token.key}'}
            )

            logger.debug(
                f'Status: {response.status_code} Reason: {response.reason}')
            logger.debug(response.json())
            # Redirect to the book list page
            return redirect(reverse_lazy('books:index'))
    else:
        form = ImportBooksForm()
    return render(request, 'books/import_books_form.html', {'form': form})


@login_required
def expenses_dashboard(request):
    # fetch the expenses per category
    queryset = Category.objects.prefetch_related(
        'books').annotate(total_expenses=Sum('books__expense'))

    # Make filter for the categories
    f = CategoriesFilter(request.GET, queryset=queryset)

    # Convert to a dictionary
    categories = dict(f.qs.values_list('name', 'total_expenses'))
    categories = {k: float(v) for k, v in categories.items()}
    total_expenses = sum(categories.values())
    category_count = len(categories)
    most_expensive_category_name = max(categories, key=categories.get)
    most_expensive_category_value = categories[most_expensive_category_name]

    # Generate the plot using Bokeh
    try:
        plot = generate_plot(categories)
    except KeyError:
        messages.error(
            request, f"You should select at least 3 categories and you selected {category_count}")
        return redirect(reverse_lazy('books:expenses_dashboard'))

    # Convert the plot to HTML components
    from bokeh.embed import components
    script, div = components(plot)

    # gather context variables
    context = {
        'filter': f,
        'div': div,
        'script': script,
        'category_count': category_count,
        'total_expenses': total_expenses,
        'categories': categories,
        'most_expensive_category_name': most_expensive_category_name,
        'most_expensive_category_value': most_expensive_category_value,
    }

    # Render the template with the plot
    return render(
        request,
        'books/expenses_dashboard.html',
        context,
    )

books/templates/books/book_detail.html
{% extends 'sidebar.html' %}

{% block title %}{{ book.title }}{% endblock %}

{% block sb_content %}
<div class="container mt-5">
    <div class="card shadow-sm">
        <div class="card-body">
            <h1 class="card-title text-primary">{{ book.title }}</h1>
            <h2 class="card-subtitle text-muted mb-3">{{ book.subtitle }}</h2>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>Category:</strong> {{ book.category }}</li>
                <li class="list-group-item"><strong>Authors:</strong> {{ book.authors }}</li>
                <li class="list-group-item"><strong>Publisher:</strong> {{ book.publisher }}</li>
                <li class="list-group-item"><strong>Published Date:</strong> {{ book.published_date }}</li>
                <li class="list-group-item"><strong>Expense:</strong> ${{ book.expense }}</li>
            </ul>
            <div class="mt-4">
                <a href="javascript:history.back()" class="btn btn-outline-secondary">Back</a>
                <a href="{% url 'books:book_update' book.id %}" class="btn btn-outline-primary">Edit</a>
                <a href="{% url 'books:book_delete' book.id %}" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock sb_content %}

books/templates/books/book_form.html
{% extends 'sidebar.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Book Form
{% endblock %}

{% block sb_content %}
    <div class="container mt-5 mb-5">
        <h1 class="text-center">{{ form.instance.id|yesno:"Edit Book,Add Book" }}</h1>
        <div class="text-end mb-3">
            <!-- Button to trigger modal -->
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addCategoryModal">
                Add a category
            </button>
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% crispy form %}
            {% comment %} <div class="mb-3">
                <label for="id_title" class="form-label">Title</label>
                <input type="text" name="title" class="form-control" id="id_title" value="{{ form.title.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="id_subtitle" class="form-label">Subtitle</label>
                <input type="text" name="subtitle" class="form-control" id="id_subtitle" value="{{ form.subtitle.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="id_authors" class="form-label">Authors</label>
                <input type="text" name="authors" class="form-control" id="id_authors" value="{{ form.authors.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="id_category" class="form-label">Category</label>
                <select name="category" class="form-select" id="id_category">
                    {% for category in form.category.field.queryset %}
                        <option value="{{ category.id }}" {% if category.id == form.category.value %}selected{% endif %}>
                            {{ category.name }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="id_publisher" class="form-label">Publisher</label>
                <input type="text" name="publisher" class="form-control" id="id_publisher" value="{{ form.publisher.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="id_published_date" class="form-label">Published Date</label>
                <input type="date" name="published_date" class="form-control" id="id_published_date" value="{{ form.published_date.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="id_expense" class="form-label">Expense</label>
                <input type="number" name="expense" class="form-control" id="id_expense" step="0.01" value="{{ form.expense.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="btn btn-primary">Save</button> {% endcomment %}
            <a href="javascript:history.back()" class="btn btn-secondary">Back</a>
        </form>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="addCategoryModal" tabindex="-1" aria-labelledby="addCategoryModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addCategoryModalLabel">Add a Category</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form
                    method="post"
                    action="{% url 'api_create_category' %}"
                    hx-post="{% url 'api_create_category' %}"
                    hx-target="#id_category"
                    hx-swap="outerHTML"
                    >
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_category_name" class="form-label">Category Name</label>
                            <input type="text" name="name" class="form-control" id="id_category_name">
                        </div>
                        <button type="submit" class="btn btn-primary">Add Category</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock sb_content %}

books/templates/books/book_list.html
{% extends 'sidebar.html' %}

{% block title %}
    Book List
{% endblock %}

<!-- include book filter -->
{% block filter_form %}
    {% include "books/filter.html" %}
{% endblock filter_form %}

{% block sb_content %}
    <div class="container mt-4">
        <h2 class="text-center mt-3">Book List</h2>
        <!-- Books CRUD buttons section -->
        <div class="text-end mb-3">
            <a href="{% url 'books:book_create' %}" class="btn btn-primary">Add Book</a>
            <a href="{% url 'books:import_books' %}" class="btn btn-dark">Import from file</a>
        </div>
        <!-- Book list table -->
        <table class="table table-striped table-bordered">
            <thead class="table-secondary">
                <tr>
                    <th>Title</th>
                    <th>Subtitle</th>
                    <th>Category</th>
                    <th>Publisher</th>
                    <th>Published Date</th>
                    <th>Expense</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for book in books %}
                <tr>
                    <td><a href="{% url 'books:book_detail' book.id %}" class="text-decoration-none">{{ book.title }}</a></td>
                    <td>{{ book.subtitle }}</td>
                    <td>{{ book.category }}</td>
                    <td>{{ book.publisher }}</td>
                    <td>{{ book.published_date }}</td>
                    <td class='text-center'>${{ book.expense }}</td>
                    <td>
                        <a href="{% url 'books:book_delete' book.id %}" class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- Pagination -->
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?{% if filter.form.data %}{{ filter.form.data.urlencode }}&{% endif %}page=1">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?{% if filter.form.data %}{{ filter.form.data.urlencode }}&{% endif %}page={{ page_obj.previous_page_number }}">Previous</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">First</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                    </li>
                {% endif %}
        
                <li class="page-item active">
                    <span class="page-link">
                        {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>
                </li>
        
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?{% if filter.form.data %}{{ filter.form.data.urlencode }}&{% endif %}page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?{% if filter.form.data %}{{ filter.form.data.urlencode }}&{% endif %}page={{ page_obj.paginator.num_pages }}">Last</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Next</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Last</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock sb_content %}

books/templates/books/category_detail.html
{% extends "sidebar.html" %}
{% load cache %}

{% block title %}{{ category.name|capfirst }} Category{% endblock title %}

{% block sb_content %}
<div class="container mt-4">
    {% comment %} Category important information {% endcomment %}
    <h1 class="text-primary">{{ category.name|capfirst }} Category</h1>
    <p><strong>Number of books:</strong> {{ category.books.count }}</p>
    <p><strong>Total expenses:</strong> ${{ category.total_expenses }}</p>

    {% comment %} Category actions {% endcomment %}
    <div class="mt-3">
        <a href="{% url 'books:category_update' category.id %}" class="btn btn-outline-primary">Edit Category</a>
        <a href="javascript:history.back()" class="btn btn-outline-secondary">Back</a>
        <a href="{% url 'books:category_delete' category.id %}" class="btn btn-danger">Delete Category</a>
    </div>

    {% comment %} List of books in the category {% endcomment %}
    {% cache 1800 category_books_list %}
    <ul class="list-group mt-3 mb-3">
        <h3 class="text-start mb-3">Books in this category</h3>
        {% for book in page_obj %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <a href="{% url 'books:book_detail' book.id %}" class="text-decoration-none text-dark">
                {{ book.title }}
            </a>
            <span class="badge bg-primary rounded-pill">${{ book.expense }}</span>
        </li>
        {% empty %}
        <li class="list-group-item">No books available in this category.</li>
        {% endfor %}
    </ul>
    <!-- Pagination -->
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
            <li class="page-item active" aria-current="page">
                <span class="page-link">{{ num }}</span>
            </li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <li class="page-item">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endcache %}
</div>
{% endblock sb_content %}

books/templates/books/category_form.html
{% extends "sidebar.html" %}
{% load crispy_forms_tags %}

{% block title %}
{% if 'create' in request.path %}Add Category{% else %}Update Category{% endif %}
{% endblock title %}

{% block sb_content %}
<div class="container mt-4">
    {% if 'create' in request.path %}<h2 class="text-center">Add Category</h2>{% else %}<h2 class="text-center">Update
        Category</h2>{% endif %}
    {% crispy form %}
    <a href="javascript:history.back()" class="btn btn-secondary">Back</a>
</div>
{% endblock sb_content %}

books/templates/books/category_list.html
{% extends "sidebar.html" %}
{% load cache %}

{% block title %}Category List{% endblock title %}

{% block sb_content %}
<div class="container mt-4">
    <h2 class="text-center mt-3">Categories</h2>
    <div class="d-flex justify-content-end mb-3">
        <a href="{% url 'books:category_create' %}" class="btn btn-primary">Add Category</a>
    </div>
    <table class="table table-striped table-bordered">
        <thead class="table-secondary">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Category Name</th>
                <th scope="col">Books Count</th>
                <th scope="col">Distribution expenses</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% cache 300 category_list %}
            {% for category in category_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'books:category_detail' category.id %}" class="text-decoration-none">{{ category.name }}</a></td>
                <td>{{ category.books.count }}</td>
                <td>${{ category.total_expenses }}</td>
                <td>
                    <a href="{% url 'books:category_update' category.id %}" class="btn btn-primary btn-sm">Edit</a>
                    <a href="{% url 'books:category_delete' category.id %}" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5" class="text-center">No categories available.</td>
            </tr>
            {% endfor %}
            {% endcache %}
        </tbody>
    </table>
</div>
{% endblock sb_content %}

books/templates/books/filter.html
<div>
    <form method="get">
        <button type="submit" class="btn btn-sm btn-primary mb-3">Apply filters</button>
        {{ filter.form.as_p }}
    </form>
</div>

books/templates/books/import_books_form.html
{% extends "sidebar.html" %}
{% load crispy_forms_tags %}

{% block title %}Import Books{% endblock title %}

{% block sb_content %}
<div class="container mt-5 mb-5">
    <h1 class="text-center">Import Books</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Import</button>
        <a href="javascript:history.back()" class="btn btn-secondary">Back</a>
    </form>
</div>
{% endblock sb_content %}

books/templates/books/object_confirm_delete.html
{% extends "sidebar.html" %}

{% block title %}Confirm Delete{% endblock title %}

{% block sb_content %}

<div class="container mt-5 text-center">
    <h2>Are you sure you want to delete "{{ object }}"?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, delete</button>
        <a href="javascript:history.back()" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock sb_content %}